# Generated by Django 3.0.2 on 2023-05-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_interest_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'managed': False},
        ),
    ]
