# Generated by Django 3.0.2 on 2023-05-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20230502_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={},
        ),
    ]
