# Generated by Django 3.0.2 on 2023-05-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20230502_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
