# Generated by Django 3.0.2 on 2023-05-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='content_txt',
            field=models.TextField(blank=True, max_length=140),
        ),
    ]
