# Generated by Django 3.0.2 on 2023-05-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_interest_content_txt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
