# Generated by Django 3.0.2 on 2023-05-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_interest_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
