# Generated by Django 3.0.2 on 2023-05-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_interest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('user', 'content_txt')},
        ),
    ]
