# Generated by Django 3.0.2 on 2023-05-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20230502_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
