# Generated by Django 3.0.2 on 2023-05-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
