# Generated by Django 3.0.2 on 2023-05-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
