# Generated by Django 3.0.2 on 2023-05-04 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enrich_user',
            field=models.ManyToManyField(blank=True, related_name='enrichir', to=settings.AUTH_USER_MODEL),
        ),
    ]
