# Generated by Django 3.0.2 on 2023-05-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_post_enrich_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrich_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
