# Generated by Django 3.0.2 on 2023-05-05 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_enrich_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest_neuron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_neuron', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
