# Generated by Django 3.0.2 on 2023-05-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_interest_neuron'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest_neuron',
        ),
    ]
