# Generated by Django 3.0.2 on 2023-05-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_delete_interest_neuron'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
