# Generated by Django 3.0.2 on 2023-05-05 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admindashoard', '0002_auto_20230505_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interest',
            new_name='Interest_neuron',
        ),
    ]
