# Generated by Django 3.0.2 on 2023-05-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashoard', '0004_auto_20230505_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest_neuron',
        ),
    ]
