# Generated by Django 3.0.2 on 2023-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admindashoard', '0005_delete_interest_neuron'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest_neuron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, max_length=140)),
                ('content', models.TextField(blank=True, max_length=140)),
            ],
        ),
    ]
